package com.myjs.sys.user.model;
// Generated 2017/2/22 �U�� 02:42:41 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LSysDepart generated by hbm2java
 */
@Entity
@Table(name = "L_SYS_DEPART", schema = "dbo", catalog = "Legal")
public class LSysDepart implements java.io.Serializable {

	private static final long serialVersionUID = -8838147575281814700L;
	private String departId;
	private String departPid;
	private String departCode;
	private String departName;
	private String departStatus;
	private Date createdate;
	private Date modifydate;
	private String modifyUserId;
	private Set<LSysUserDepart> LSysUserDeparts = new HashSet<LSysUserDepart>(0);

	public LSysDepart() {
	}

	public LSysDepart(String departId, String departCode, String departName) {
		this.departId = departId;
		this.departCode = departCode;
		this.departName = departName;
	}

	public LSysDepart(String departId, String departPid, String departCode, String departName, String departStatus,
			Date createdate, Date modifydate, String modifyUserId, Set<LSysUserDepart> LSysUserDeparts) {
		this.departId = departId;
		this.departPid = departPid;
		this.departCode = departCode;
		this.departName = departName;
		this.departStatus = departStatus;
		this.createdate = createdate;
		this.modifydate = modifydate;
		this.modifyUserId = modifyUserId;
		this.LSysUserDeparts = LSysUserDeparts;
	}

	@Id

	@Column(name = "DEPART_ID", unique = true, nullable = false, length = 50)
	public String getDepartId() {
		return this.departId;
	}

	public void setDepartId(String departId) {
		this.departId = departId;
	}

	@Column(name = "DEPART_PID", length = 50)
	public String getDepartPid() {
		return this.departPid;
	}

	public void setDepartPid(String departPid) {
		this.departPid = departPid;
	}

	@Column(name = "DEPART_CODE", nullable = false, length = 5)
	public String getDepartCode() {
		return this.departCode;
	}

	public void setDepartCode(String departCode) {
		this.departCode = departCode;
	}

	@Column(name = "DEPART_NAME", nullable = false, length = 40)
	public String getDepartName() {
		return this.departName;
	}

	public void setDepartName(String departName) {
		this.departName = departName;
	}

	@Column(name = "DEPART_STATUS", length = 1)
	public String getDepartStatus() {
		return this.departStatus;
	}

	public void setDepartStatus(String departStatus) {
		this.departStatus = departStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATEDATE", length = 23)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFYDATE", length = 23)
	public Date getModifydate() {
		return this.modifydate;
	}

	public void setModifydate(Date modifydate) {
		this.modifydate = modifydate;
	}

	@Column(name = "MODIFY_USER_ID", length = 50)
	public String getModifyUserId() {
		return this.modifyUserId;
	}

	public void setModifyUserId(String modifyUserId) {
		this.modifyUserId = modifyUserId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "LSysDepart")
	public Set<LSysUserDepart> getLSysUserDeparts() {
		return this.LSysUserDeparts;
	}

	public void setLSysUserDeparts(Set<LSysUserDepart> LSysUserDeparts) {
		this.LSysUserDeparts = LSysUserDeparts;
	}

}
