package com.myjs.sys.user.model;
// Generated 2017/2/22 �U�� 02:42:41 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LSysUserDepart generated by hbm2java
 */
@Entity
@Table(name = "L_SYS_USER_DEPART", schema = "dbo", catalog = "Legal")
public class LSysUserDepart implements java.io.Serializable {

	private static final long serialVersionUID = 3049904662154177687L;
	private String userDepartId;
	private LSysDepart LSysDepart;
	private LSysUser LSysUser;
	private String isLeader;
	private String isDelete;
	private Date createdate;
	private Date modifydate;
	private String modifyUserId;

	public LSysUserDepart() {
	}

	public LSysUserDepart(String userDepartId, LSysDepart LSysDepart, LSysUser LSysUser, String isLeader,
			String isDelete) {
		this.userDepartId = userDepartId;
		this.LSysDepart = LSysDepart;
		this.LSysUser = LSysUser;
		this.isLeader = isLeader;
		this.isDelete = isDelete;
	}

	public LSysUserDepart(String userDepartId, LSysDepart LSysDepart, LSysUser LSysUser, String isLeader,
			String isDelete, Date createdate, Date modifydate, String modifyUserId) {
		this.userDepartId = userDepartId;
		this.LSysDepart = LSysDepart;
		this.LSysUser = LSysUser;
		this.isLeader = isLeader;
		this.isDelete = isDelete;
		this.createdate = createdate;
		this.modifydate = modifydate;
		this.modifyUserId = modifyUserId;
	}

	@Id

	@Column(name = "USER_DEPART_ID", unique = true, nullable = false, length = 50)
	public String getUserDepartId() {
		return this.userDepartId;
	}

	public void setUserDepartId(String userDepartId) {
		this.userDepartId = userDepartId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEPART_ID", nullable = false)
	public LSysDepart getLSysDepart() {
		return this.LSysDepart;
	}

	public void setLSysDepart(LSysDepart LSysDepart) {
		this.LSysDepart = LSysDepart;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false)
	public LSysUser getLSysUser() {
		return this.LSysUser;
	}

	public void setLSysUser(LSysUser LSysUser) {
		this.LSysUser = LSysUser;
	}

	@Column(name = "IS_LEADER", nullable = false, length = 1)
	public String getIsLeader() {
		return this.isLeader;
	}

	public void setIsLeader(String isLeader) {
		this.isLeader = isLeader;
	}

	@Column(name = "IS_DELETE", nullable = false, length = 1)
	public String getIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(String isDelete) {
		this.isDelete = isDelete;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATEDATE", length = 23)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFYDATE", length = 23)
	public Date getModifydate() {
		return this.modifydate;
	}

	public void setModifydate(Date modifydate) {
		this.modifydate = modifydate;
	}

	@Column(name = "MODIFY_USER_ID", length = 50)
	public String getModifyUserId() {
		return this.modifyUserId;
	}

	public void setModifyUserId(String modifyUserId) {
		this.modifyUserId = modifyUserId;
	}

}
