package com.myjs.cek.checkform.model;
// Generated 2017/3/23 �U�� 01:55:51 by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LCekCheckformColumn generated by hbm2java
 */
@Entity
@Table(name = "L_CEK_CHECKFORM_COLUMN", schema = "dbo", catalog = "Legal")
public class LCekCheckformColumn implements java.io.Serializable {

	private static final long serialVersionUID = -8633256675256751848L;
	private String checkformColumnId;
	private String checkformId;
	private String columnId;
	private String isDelete;
	private LCekCheckform LCekCheckform;
	private LCekColumn LCekColumn;

	public LCekCheckformColumn() {
	}

	public LCekCheckformColumn(String checkformColumnId, String checkformId, String columnId, String isDelete) {
		this.checkformColumnId = checkformColumnId;
		this.checkformId = checkformId;
		this.columnId = columnId;
		this.isDelete = isDelete;
	}

	@Id

	@Column(name = "checkform_column_id", unique = true, nullable = false, length = 50)
	public String getCheckformColumnId() {
		return this.checkformColumnId;
	}

	public void setCheckformColumnId(String checkformColumnId) {
		this.checkformColumnId = checkformColumnId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "checkform_id", nullable = false)
	public LCekCheckform getLCekCheckform() {
		return this.LCekCheckform;
	}

	public void setLCekCheckform(LCekCheckform LCekCheckform) {
		this.LCekCheckform = LCekCheckform;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "column_id", nullable = false)
	public LCekColumn getLCekColumn() {
		return this.LCekColumn;
	}

	public void setLCekColumn(LCekColumn LCekColumn) {
		this.LCekColumn = LCekColumn;
	}

	public String getIsDelete() {
		return isDelete;
	}

	public void setIsDelete(String isDelete) {
		this.isDelete = isDelete;
	}

	public String getCheckformId() {
		return checkformId;
	}

	public void setCheckformId(String checkformId) {
		this.checkformId = checkformId;
	}

	public String getColumnId() {
		return columnId;
	}

	public void setColumnId(String columnId) {
		this.columnId = columnId;
	}

	
}
