package com.myjs.cek.checkform.model;
// Generated 2017/4/24 �U�� 01:55:51 by Jia

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * LCekCheckformColumn generated by hbm2java
 */
@Entity
@Table(name = "L_CEK_CHECKFORM_COLUMN", schema = "dbo", catalog = "Legal")
public class LCekCheckformFile implements java.io.Serializable {

	private static final long serialVersionUID = -8633256675256751848L;
	private String checkformFileId;
	private String checkformId;
	private String fileId;
	private String isDelete;
//	private LCekCheckform LCekCheckform;
//	private LCekColumn LCekColumn;

	public LCekCheckformFile() {
	}

	public LCekCheckformFile(String checkformFileId, String checkformId, String fileId, String isDelete) {
		this.checkformFileId = checkformFileId;
		this.checkformId = checkformId;
		this.fileId = fileId;
		this.isDelete = isDelete;
	}

	public String getCheckformFileId() {
		return checkformFileId;
	}

	public void setCheckformFileId(String checkformFileId) {
		this.checkformFileId = checkformFileId;
	}

	public String getCheckformId() {
		return checkformId;
	}

	public void setCheckformId(String checkformId) {
		this.checkformId = checkformId;
	}

	public String getFileId() {
		return fileId;
	}

	public void setFileId(String fileId) {
		this.fileId = fileId;
	}

	public String getIsDelete() {
		return isDelete;
	}

	public void setIsDelete(String isDelete) {
		this.isDelete = isDelete;
	}

	
}
