package com.myjs.cek.checkform.model;
// Generated 2017/3/23 �U�� 01:55:51 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LCekColumn generated by hbm2java
 */
@Entity
@Table(name = "L_CEK_COLUMN", schema = "dbo", catalog = "Legal")
public class LCekColumn implements java.io.Serializable {

	private static final long serialVersionUID = -7195568467150831839L;
	private String columnId;
	private String columnName;
	private String columnAlert;
	private String columnIsdefault;
	private String columnType;
	private int columnSize;
	private String columnStatus;
	private String createUserId;
	private Date createDatetime;
	private String modifyUserId;
	private Date modifyDatetime;
	private String vocheckformcolumnId;// 放Mapping的checkformcolumnId
	private String voisdelete;// 放Mapping的Isdelete
	
	public LCekColumn() {
	}

	public LCekColumn(String columnId, String columnIsdefault, String columnType, int columnSize, String columnStatus) {
		this.columnId = columnId;
		this.columnIsdefault = columnIsdefault;
		this.columnType = columnType;
		this.columnSize = columnSize;
		this.columnStatus = columnStatus;
	}

	public LCekColumn(String columnId, String columnName, String columnAlert, String columnIsdefault, String columnType,
			int columnSize, String columnStatus, String createUserId, Date createDatetime, String modifyUserId,
			Date modifyDatetime) {
		this.columnId = columnId;
		this.columnName = columnName;
		this.columnAlert = columnAlert;
		this.columnIsdefault = columnIsdefault;
		this.columnType = columnType;
		this.columnSize = columnSize;
		this.columnStatus = columnStatus;
		this.createUserId = createUserId;
		this.createDatetime = createDatetime;
		this.modifyUserId = modifyUserId;
		this.modifyDatetime = modifyDatetime;
	}

	@Id

	@Column(name = "column_id", unique = true, nullable = false, length = 50)
	public String getColumnId() {
		return this.columnId;
	}

	public void setColumnId(String columnId) {
		this.columnId = columnId;
	}

	@Column(name = "column_name", length = 50)
	public String getColumnName() {
		return this.columnName;
	}

	public void setColumnName(String columnName) {
		this.columnName = columnName;
	}

	@Column(name = "column_alert", length = 50)
	public String getColumnAlert() {
		return this.columnAlert;
	}

	public void setColumnAlert(String columnAlert) {
		this.columnAlert = columnAlert;
	}

	@Column(name = "column_isdefault", nullable = false, length = 1)
	public String getColumnIsdefault() {
		return this.columnIsdefault;
	}

	public void setColumnIsdefault(String columnIsdefault) {
		this.columnIsdefault = columnIsdefault;
	}

	@Column(name = "column_type", nullable = false, length = 10)
	public String getColumnType() {
		return this.columnType;
	}

	public void setColumnType(String columnType) {
		this.columnType = columnType;
	}

	@Column(name = "column_size", nullable = false)
	public int getColumnSize() {
		return this.columnSize;
	}

	public void setColumnSize(int columnSize) {
		this.columnSize = columnSize;
	}

	@Column(name = "column_status", nullable = false, length = 1)
	public String getColumnStatus() {
		return this.columnStatus;
	}

	public void setColumnStatus(String columnStatus) {
		this.columnStatus = columnStatus;
	}

	@Column(name = "create_user_id", length = 20)
	public String getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(String createUserId) {
		this.createUserId = createUserId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_datetime", length = 23)
	public Date getCreateDatetime() {
		return this.createDatetime;
	}

	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	@Column(name = "modify_user_id", length = 20)
	public String getModifyUserId() {
		return this.modifyUserId;
	}

	public void setModifyUserId(String modifyUserId) {
		this.modifyUserId = modifyUserId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_datetime", length = 23)
	public Date getModifyDatetime() {
		return this.modifyDatetime;
	}

	public void setModifyDatetime(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	public String getVocheckformcolumnId() {
		return vocheckformcolumnId;
	}

	public void setVocheckformcolumnId(String vocheckformcolumnId) {
		this.vocheckformcolumnId = vocheckformcolumnId;
	}

	public String getVoisdelete() {
		return voisdelete;
	}

	public void setVoisdelete(String voisdelete) {
		this.voisdelete = voisdelete;
	}

	
}
