package com.myjs.cek.checkform.model;
// Generated 2017/3/23 �U�� 01:55:51 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LCekCheckform generated by hbm2java
 */
@Entity
@Table(name = "L_CEK_CHECKFORM", schema = "dbo", catalog = "Legal")
public class LCekCheckform implements java.io.Serializable {

	private static final long serialVersionUID = 4694110629385480506L;
	private String checkformId;
	private String checkformName;
	private String checkformType;
	private String createUserId;
	private Date createDatetime;
	private String modifyUserId;
	private Date modifyDatetime;
	private String status;
	private String flowId;
	private String checkformCode;

	public LCekCheckform() {
	}

	public LCekCheckform(String checkformId, String checkformName, String createUserId, Date createDatetime,
			String status) {
		this.checkformId = checkformId;
		this.checkformName = checkformName;
		this.createUserId = createUserId;
		this.createDatetime = createDatetime;
		this.status = status;
	}

	public LCekCheckform(String checkformId, String checkformName, String checkformType, String createUserId,
			Date createDatetime, String modifyUserId, Date modifyDatetime, String status, String flowId,
			String checkformCode) {
		this.checkformId = checkformId;
		this.checkformName = checkformName;
		this.checkformType = checkformType;
		this.createUserId = createUserId;
		this.createDatetime = createDatetime;
		this.modifyUserId = modifyUserId;
		this.modifyDatetime = modifyDatetime;
		this.status = status;
		this.flowId = flowId;
		this.checkformCode = checkformCode;
	}

	@Id

	@Column(name = "checkform_id", unique = true, nullable = false, length = 50)
	public String getCheckformId() {
		return this.checkformId;
	}

	public void setCheckformId(String checkformId) {
		this.checkformId = checkformId;
	}

	@Column(name = "checkform_name", nullable = false, length = 20)
	public String getCheckformName() {
		return this.checkformName;
	}

	public void setCheckformName(String checkformName) {
		this.checkformName = checkformName;
	}

	@Column(name = "checkform_type", length = 50)
	public String getCheckformType() {
		return this.checkformType;
	}

	public void setCheckformType(String checkformType) {
		this.checkformType = checkformType;
	}

	@Column(name = "create_user_id", nullable = false, length = 50)
	public String getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(String createUserId) {
		this.createUserId = createUserId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_datetime", nullable = false, length = 23)
	public Date getCreateDatetime() {
		return this.createDatetime;
	}

	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	@Column(name = "modify_user_id", length = 50)
	public String getModifyUserId() {
		return this.modifyUserId;
	}

	public void setModifyUserId(String modifyUserId) {
		this.modifyUserId = modifyUserId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_datetime", length = 23)
	public Date getModifyDatetime() {
		return this.modifyDatetime;
	}

	public void setModifyDatetime(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	@Column(name = "status", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "flow_id", length = 50)
	public String getFlowId() {
		return this.flowId;
	}

	public void setFlowId(String flowId) {
		this.flowId = flowId;
	}

	@Column(name = "checkform_code", length = 20)
	public String getCheckformCode() {
		return this.checkformCode;
	}

	public void setCheckformCode(String checkformCode) {
		this.checkformCode = checkformCode;
	}

}
