package com.myjs.cek.checkform.model;
// Generated 2017/3/22 �U�� 05:01:21 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LCekCheckformId generated by hbm2java
 */
@Embeddable
public class LCekCheckformId implements java.io.Serializable {

	private static final long serialVersionUID = 6916496326170521180L;
	private String checkformId;
	private String checkformName;
	private String checkformType;
	private String createUserId;
	private Date createDatetime;
	private String modifyUserId;
	private Date modifyDatetime;
	private String status;
	private String flowId;
	private String checkformCode;

	public LCekCheckformId() {
	}

	public LCekCheckformId(String checkformId, String checkformName, String createUserId, Date createDatetime,
			String status) {
		this.checkformId = checkformId;
		this.checkformName = checkformName;
		this.createUserId = createUserId;
		this.createDatetime = createDatetime;
		this.status = status;
	}

	public LCekCheckformId(String checkformId, String checkformName, String checkformType, String createUserId,
			Date createDatetime, String modifyUserId, Date modifyDatetime, String status, String flowId,
			String checkformCode) {
		this.checkformId = checkformId;
		this.checkformName = checkformName;
		this.checkformType = checkformType;
		this.createUserId = createUserId;
		this.createDatetime = createDatetime;
		this.modifyUserId = modifyUserId;
		this.modifyDatetime = modifyDatetime;
		this.status = status;
		this.flowId = flowId;
		this.checkformCode = checkformCode;
	}

	@Column(name = "checkform_id", nullable = false, length = 36)
	public String getCheckformId() {
		return this.checkformId;
	}

	public void setCheckformId(String checkformId) {
		this.checkformId = checkformId;
	}

	@Column(name = "checkform_name", nullable = false, length = 20)
	public String getCheckformName() {
		return this.checkformName;
	}

	public void setCheckformName(String checkformName) {
		this.checkformName = checkformName;
	}

	@Column(name = "checkform_type", length = 50)
	public String getCheckformType() {
		return this.checkformType;
	}

	public void setCheckformType(String checkformType) {
		this.checkformType = checkformType;
	}

	@Column(name = "create_user_id", nullable = false, length = 50)
	public String getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(String createUserId) {
		this.createUserId = createUserId;
	}

	@Column(name = "create_datetime", nullable = false, length = 23)
	public Date getCreateDatetime() {
		return this.createDatetime;
	}

	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	@Column(name = "modify_user_id", length = 50)
	public String getModifyUserId() {
		return this.modifyUserId;
	}

	public void setModifyUserId(String modifyUserId) {
		this.modifyUserId = modifyUserId;
	}

	@Column(name = "modify_datetime", length = 23)
	public Date getModifyDatetime() {
		return this.modifyDatetime;
	}

	public void setModifyDatetime(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	@Column(name = "status", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "flow_id", length = 50)
	public String getFlowId() {
		return this.flowId;
	}

	public void setFlowId(String flowId) {
		this.flowId = flowId;
	}

	@Column(name = "checkform_code", length = 20)
	public String getCheckformCode() {
		return this.checkformCode;
	}

	public void setCheckformCode(String checkformCode) {
		this.checkformCode = checkformCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LCekCheckformId))
			return false;
		LCekCheckformId castOther = (LCekCheckformId) other;

		return ((this.getCheckformId() == castOther.getCheckformId()) || (this.getCheckformId() != null
				&& castOther.getCheckformId() != null && this.getCheckformId().equals(castOther.getCheckformId())))
				&& ((this.getCheckformName() == castOther.getCheckformName())
						|| (this.getCheckformName() != null && castOther.getCheckformName() != null
								&& this.getCheckformName().equals(castOther.getCheckformName())))
				&& ((this.getCheckformType() == castOther.getCheckformType())
						|| (this.getCheckformType() != null && castOther.getCheckformType() != null
								&& this.getCheckformType().equals(castOther.getCheckformType())))
				&& ((this.getCreateUserId() == castOther.getCreateUserId())
						|| (this.getCreateUserId() != null && castOther.getCreateUserId() != null
								&& this.getCreateUserId().equals(castOther.getCreateUserId())))
				&& ((this.getCreateDatetime() == castOther.getCreateDatetime())
						|| (this.getCreateDatetime() != null && castOther.getCreateDatetime() != null
								&& this.getCreateDatetime().equals(castOther.getCreateDatetime())))
				&& ((this.getModifyUserId() == castOther.getModifyUserId())
						|| (this.getModifyUserId() != null && castOther.getModifyUserId() != null
								&& this.getModifyUserId().equals(castOther.getModifyUserId())))
				&& ((this.getModifyDatetime() == castOther.getModifyDatetime())
						|| (this.getModifyDatetime() != null && castOther.getModifyDatetime() != null
								&& this.getModifyDatetime().equals(castOther.getModifyDatetime())))
				&& ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null
						&& castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())))
				&& ((this.getFlowId() == castOther.getFlowId()) || (this.getFlowId() != null
						&& castOther.getFlowId() != null && this.getFlowId().equals(castOther.getFlowId())))
				&& ((this.getCheckformCode() == castOther.getCheckformCode())
						|| (this.getCheckformCode() != null && castOther.getCheckformCode() != null
								&& this.getCheckformCode().equals(castOther.getCheckformCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCheckformId() == null ? 0 : this.getCheckformId().hashCode());
		result = 37 * result + (getCheckformName() == null ? 0 : this.getCheckformName().hashCode());
		result = 37 * result + (getCheckformType() == null ? 0 : this.getCheckformType().hashCode());
		result = 37 * result + (getCreateUserId() == null ? 0 : this.getCreateUserId().hashCode());
		result = 37 * result + (getCreateDatetime() == null ? 0 : this.getCreateDatetime().hashCode());
		result = 37 * result + (getModifyUserId() == null ? 0 : this.getModifyUserId().hashCode());
		result = 37 * result + (getModifyDatetime() == null ? 0 : this.getModifyDatetime().hashCode());
		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result + (getFlowId() == null ? 0 : this.getFlowId().hashCode());
		result = 37 * result + (getCheckformCode() == null ? 0 : this.getCheckformCode().hashCode());
		return result;
	}

}
