package com.myjs.cek.recordcheckform.model;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * LCekRecordCheckform generated by JiaJia
 */
@Entity
@Table(name = "L_CEK_RECORD_CHECKFORM", schema = "dbo", catalog = "Legal")
public class LCekRecordCheckform implements java.io.Serializable{
	
	private static final long serialVersionUID = 6111428884957384848L;
	private String recordCheckformId;
	private String checkformId;
	private String flowsubId;
	private int status;
	private String modifyUserId;
	private Date modifyDatetime;
	private String mappingtableId;
	private String receivedUserId;

	// VO加上去的
	private String signedId;
	private int caseId;
	private String bankName;
	private String prodName;
	private String payer;
	private String payerRole;
	private String type;
	private int periods;
	private Date paytimeStart;
	private Date paytimeEnd;
	private int ammountP;
	private int ammountSum;
	private Date applyDate;
	private String applyUserId;
	private String applyUserName;

	public LCekRecordCheckform() {

	}

	public LCekRecordCheckform(String recordCheckformId, String checkformId, String flowsubId,
			int status, String modifyUserId, Date modifyDatetime, String mappingtableId, String receivedUserId) {
		this.recordCheckformId = recordCheckformId;
		this.checkformId = checkformId;
		this.flowsubId = flowsubId;
		this.status = status;
		this.modifyUserId = modifyUserId;
		this.modifyDatetime = modifyDatetime;
		this.mappingtableId = mappingtableId;
		this.receivedUserId = receivedUserId;
	}

	public String getRecordCheckformId() {
		return recordCheckformId;
	}

	public void setRecordCheckformId(String recordCheckformId) {
		this.recordCheckformId = recordCheckformId;
	}

	public String getCheckformId() {
		return checkformId;
	}

	public void setCheckformId(String checkformId) {
		this.checkformId = checkformId;
	}

	public String getFlowsubId() {
		return flowsubId;
	}

	public void setFlowsubId(String flowsubId) {
		this.flowsubId = flowsubId;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public String getModifyUserId() {
		return modifyUserId;
	}

	public void setModifyUserId(String modifyUserId) {
		this.modifyUserId = modifyUserId;
	}

	public Date getModifyDatetime() {
		return modifyDatetime;
	}

	public void setModifyDatetime(Date modifyDatetime) {
		this.modifyDatetime = modifyDatetime;
	}

	public String getMappingtableId() {
		return mappingtableId;
	}

	public void setMappingtableId(String mappingtableId) {
		this.mappingtableId = mappingtableId;
	}

	public String getSignedId() {
		return signedId;
	}

	public void setSignedId(String signedId) {
		this.signedId = signedId;
	}

	public int getCaseId() {
		return caseId;
	}

	public void setCaseId(int caseId) {
		this.caseId = caseId;
	}

	public String getBankName() {
		return bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public String getProdName() {
		return prodName;
	}

	public void setProdName(String prodName) {
		this.prodName = prodName;
	}

	public String getPayer() {
		return payer;
	}

	public void setPayer(String payer) {
		this.payer = payer;
	}

	public String getPayerRole() {
		return payerRole;
	}

	public void setPayerRole(String payerRole) {
		this.payerRole = payerRole;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public int getPeriods() {
		return periods;
	}

	public void setPeriods(int periods) {
		this.periods = periods;
	}

	public Date getPaytimeStart() {
		return paytimeStart;
	}

	public void setPaytimeStart(Date paytimeStart) {
		this.paytimeStart = paytimeStart;
	}

	public Date getPaytimeEnd() {
		return paytimeEnd;
	}

	public void setPaytimeEnd(Date paytimeEnd) {
		this.paytimeEnd = paytimeEnd;
	}

	public int getAmmountP() {
		return ammountP;
	}

	public void setAmmountP(int ammountP) {
		this.ammountP = ammountP;
	}

	public int getAmmountSum() {
		return ammountSum;
	}

	public void setAmmountSum(int ammountSum) {
		this.ammountSum = ammountSum;
	}

	public Date getApplyDate() {
		return applyDate;
	}

	public void setApplyDate(Date applyDate) {
		this.applyDate = applyDate;
	}

	public String getApplyUserId() {
		return applyUserId;
	}

	public void setApplyUserId(String applyUserId) {
		this.applyUserId = applyUserId;
	}

	public String getReceivedUserId() {
		return receivedUserId;
	}

	public void setReceivedUserId(String receivedUserId) {
		this.receivedUserId = receivedUserId;
	}

	public String getApplyUserName() {
		return applyUserName;
	}

	public void setApplyUserName(String applyUserName) {
		this.applyUserName = applyUserName;
	}
	
}
