package com.myjs.cek.recordcheckform.model;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * LCekRecordCheckform generated by JiaJia
 */
@Entity
@Table(name = "V_SMART_RELAINFO", schema = "dbo", catalog = "Legal")
public class LCekSignedRelaInfo implements java.io.Serializable {

	
	private static final long serialVersionUID = -8426003254920606986L;
	private Long Row_ID;
	private int Case_ID;
	private String Name;
	private String ID;
	private String Rela_kind;
	private String Role;
	private int P_ID;

	public LCekSignedRelaInfo() {

	}

	public LCekSignedRelaInfo(int Row_ID, int Case_ID, String Name, String ID, String Rela_kind, String Role, int P_ID) {
		this.Case_ID = Case_ID;
		this.Name = Name;
		this.ID = ID;
		this.Rela_kind = Rela_kind;
		this.Role = Role;
		this.P_ID = P_ID;
	}

	public Long getRow_ID() {
		return Row_ID;
	}

	public void setRow_ID(Long row_ID) {
		Row_ID = row_ID;
	}

	public int getCase_ID() {
		return Case_ID;
	}

	public void setCase_ID(int case_ID) {
		Case_ID = case_ID;
	}

	public String getName() {
		return Name;
	}

	public void setName(String name) {
		Name = name;
	}

	public String getID() {
		return ID;
	}

	public void setID(String iD) {
		ID = iD;
	}

	public String getRela_kind() {
		return Rela_kind;
	}

	public void setRela_kind(String rela_kind) {
		Rela_kind = rela_kind;
	}

	public String getRole() {
		return Role;
	}

	public void setRole(String role) {
		Role = role;
	}

	public int getP_ID() {
		return P_ID;
	}

	public void setP_ID(int p_ID) {
		P_ID = p_ID;
	}

	
}
