package com.myjs.cek.recordcheckform.model;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * LCekRecordCheckform generated by JiaJia
 */
@Entity
@Table(name = "V_SMART_CASEINFO", schema = "dbo", catalog = "Legal")
public class LCekSignedCaseInfo implements java.io.Serializable {

	private static final long serialVersionUID = 906044964531133143L;

	private int Case_ID;
	private Byte Batch_NO;
	private String Prod_ID;
	private String CCard_num;
	private String PayCode;
	private String Currency_kind;
	private BigDecimal Exchange_rate;
	private int PriDebt_amount;
	private int Debt_amount;
	private Date QDate;
	private String AccountAge;
	private String Case_status;
	private Date Assigned_dt;
	private String Assigned_er;
	private Date PreAssigned_dt;
	private String PreAssigned_er;
	private Date Record_dt;
	private String Record_er;
	private Date Update_dt;
	private String Update_er;
	private String Reason;
	private String ctCase_interest;
	private Date ctCase_d;
	private Date gvCCard_d;
	private Date kiCCard_d;
	private Date cpInterest_d;
	private Date tnBadDebt_d;
	private Date tnPress_d;
	private Date stInterest_d;
	private String CanCost_amount;
	private Date shPay_d;
	private String DelayPay_months;
	private String PreLoanCash;
	private String Bank_other;
	private Date LCost_d;
	private String LCost_amount;
	private Date LPay_d;
	private int LPay_amount;
	private String Pay_Notes;
	private String CasePS;
	private String A_Capital;
	private String A_CFInterest;
	private String A_Interest;
	private String A_BKInterest;
	private String A_Other;
	private String A_Total;
	private String A_SIF;
	private String B_Capital;
	private String B_CFInterest;
	private String B_Interest;
	private String B_BKInterest;
	private String B_Other;
	private String B_Total;
	private String B_SIF;
	private Date ITDate;
	private String Interest_Period;
	private String Interest_kind;
	private BigDecimal Interest_Rate;
	private BigDecimal BK_Rate;
	private BigDecimal Disct_Capital;
	private BigDecimal Disct_IT;
	private BigDecimal Disct_ctCaseIT;
	private BigDecimal Disct_bkIT;
	private BigDecimal Disct_Other;
	private String LoanBank;
	private String Stat_MailedCnt;
	private String Stat_PullFLCnt;
	private String Stat_VisitedCnt;
	private String Stat_PMTAmt;
	private String Stat_PTPCnt;
	private String Stat_BPCnt;
	private String Stat_CalledCnt;
	private String CaseMarkContent;
	private String SecondHand_type;
	private String tnBadDebt_amt;
	private int otherDebt_amt;
	private String PMS_flag;
	private String insider_amt;
	private String outsider_amt;
	private Date sider_d;
	private int G_ID;
	private String Prod_Name;
	private String Bank_ID;
	private String Bank_name;
	private String Bank_alias;
	
	//add By Jia 2017-05-10 VO
	private String name;
	private String ID;
	private String O_or_C;

	public LCekSignedCaseInfo() {

	}

	public LCekSignedCaseInfo(int Case_ID, Byte Batch_NO, String Prod_ID, String CCard_num, String PayCode,
			String Currency_kind, BigDecimal Exchange_rate, int PriDebt_amount, int Debt_amount, Date QDate,
			String AccountAge, String Case_status, Date Assigned_dt, String Assigned_er, Date PreAssigned_dt,
			String PreAssigned_er, Date Record_dt, String Record_er, Date Update_dt, String Update_er, String Reason,
			String ctCase_interest, Date ctCase_d, Date gvCCard_d, Date kiCCard_d, Date cpInterest_d, Date tnBadDebt_d,
			Date tnPress_d, Date stInterest_d, String CanCost_amount, Date shPay_d, String DelayPay_months,
			String PreLoanCash, String Bank_other, Date LCost_d, String LCost_amount, Date LPay_d, int LPay_amount,
			String Pay_Notes, String CasePS, String A_Capital, String A_CFInterest, String A_Interest, String A_BKInterest,
			String A_Other, String A_Total, String A_SIF, String B_Capital, String B_CFInterest, String B_Interest, String B_BKInterest,
			String B_Other, String B_Total, String B_SIF, Date ITDate, String Interest_Period, String Interest_kind,
			BigDecimal Interest_Rate, BigDecimal BK_Rate, BigDecimal Disct_Capital, BigDecimal Disct_IT,
			BigDecimal Disct_ctCaseIT, BigDecimal Disct_bkIT, BigDecimal Disct_Other, String LoanBank,
			String Stat_MailedCnt, String Stat_PullFLCnt, String Stat_VisitedCnt, String Stat_PMTAmt,
			String Stat_PTPCnt, String Stat_BPCnt, String Stat_CalledCnt, String CaseMarkContent,
			String SecondHand_type, String tnBadDebt_amt, int otherDebt_amt, String PMS_flag, String insider_amt,
			String outsider_amt, Date sider_d, int G_ID, String Prod_Name, String Bank_ID, String Bank_name,
			String Bank_alias) {
		this.Case_ID = Case_ID;
		this.Batch_NO = Batch_NO;
		this.Prod_ID = Prod_ID;
		this.CCard_num = CCard_num;
		this.PayCode = PayCode;
		this.Currency_kind = Currency_kind;
		this.Exchange_rate = Exchange_rate;
		this.PriDebt_amount = PriDebt_amount;
		this.Debt_amount = Debt_amount;
		this.QDate = QDate;
		this.AccountAge = AccountAge;
		this.Case_status = Case_status;
		this.Assigned_dt = Assigned_dt;
		this.Assigned_dt = Assigned_dt;
		this.PreAssigned_dt = PreAssigned_dt;
		this.PreAssigned_er = PreAssigned_er;
		this.Record_dt = Record_dt;
		this.Record_er = Record_er;
		this.Update_dt = Update_dt;
		this.Update_er = Update_er;
		this.Reason = Reason;
		this.ctCase_interest = ctCase_interest;
		this.ctCase_d = ctCase_d;
		this.gvCCard_d = gvCCard_d;
		this.kiCCard_d = kiCCard_d;
		this.cpInterest_d = cpInterest_d;
		this.tnBadDebt_d = tnBadDebt_d;
		this.tnPress_d = tnPress_d;
		this.stInterest_d = stInterest_d;
		this.CanCost_amount = CanCost_amount;
		this.shPay_d = shPay_d;
		this.DelayPay_months = DelayPay_months;
		this.PreLoanCash = PreLoanCash;
		this.Bank_other = Bank_other;
		this.LCost_d = LCost_d;
		this.LCost_amount = LCost_amount;
		this.LPay_d = LPay_d;
		this.LPay_amount = LPay_amount;
		this.Pay_Notes = Pay_Notes;
		this.CasePS = CasePS;
		this.A_Capital = A_Capital;
		this.A_CFInterest = A_CFInterest;
		this.A_Interest = A_Interest;
		this.A_BKInterest = A_BKInterest;
		this.A_Other = A_Other;
		this.A_Total = A_Total;
		this.A_SIF = A_SIF;
		this.B_Capital = B_Capital;
		this.B_CFInterest = B_CFInterest;
		this.B_Interest = B_Interest;
		this.B_BKInterest = B_BKInterest;
		this.B_Other = B_Other;
		this.B_Total = B_Total;
		this.B_SIF = B_SIF;
		this.ITDate = ITDate;
		this.Interest_Period = Interest_Period;
		this.Interest_kind = Interest_kind;
		this.Interest_Rate = Interest_Rate;
		this.BK_Rate = BK_Rate;
		this.Disct_Capital = Disct_Capital;
		this.Disct_IT = Disct_IT;
		this.Disct_ctCaseIT = Disct_ctCaseIT;
		this.Disct_bkIT = Disct_bkIT;
		this.Disct_Other = Disct_Other;
		this.LoanBank = LoanBank;
		this.Stat_MailedCnt = Stat_MailedCnt;
		this.Stat_PullFLCnt = Stat_PullFLCnt;
		this.Stat_VisitedCnt = Stat_VisitedCnt;
		this.Stat_PMTAmt = Stat_PMTAmt;
		this.Stat_PTPCnt = Stat_PTPCnt;
		this.Stat_BPCnt = Stat_BPCnt;
		this.Stat_CalledCnt = Stat_CalledCnt;
		this.CaseMarkContent = CaseMarkContent;
		this.SecondHand_type = SecondHand_type;
		this.tnBadDebt_amt = tnBadDebt_amt;
		this.otherDebt_amt = otherDebt_amt;
		this.PMS_flag = PMS_flag;
		this.insider_amt = insider_amt;
		this.outsider_amt = outsider_amt;
		this.sider_d = sider_d;
		this.G_ID = G_ID;
		this.Prod_Name = Prod_Name;
		this.Bank_ID = Bank_ID;
		this.Bank_name = Bank_name;
		this.Bank_alias = Bank_alias;
	}

	public int getCase_ID() {
		return Case_ID;
	}

	public void setCase_ID(int case_ID) {
		Case_ID = case_ID;
	}

	public Byte getBatch_NO() {
		return Batch_NO;
	}

	public void setBatch_NO(Byte batch_NO) {
		Batch_NO = batch_NO;
	}

	public String getProd_ID() {
		return Prod_ID;
	}

	public void setProd_ID(String prod_ID) {
		Prod_ID = prod_ID;
	}

	public String getCCard_num() {
		return CCard_num;
	}

	public void setCCard_num(String cCard_num) {
		CCard_num = cCard_num;
	}

	public String getPayCode() {
		return PayCode;
	}

	public void setPayCode(String payCode) {
		PayCode = payCode;
	}

	public String getCurrency_kind() {
		return Currency_kind;
	}

	public void setCurrency_kind(String currency_kind) {
		Currency_kind = currency_kind;
	}

	public BigDecimal getExchange_rate() {
		return Exchange_rate;
	}

	public void setExchange_rate(BigDecimal exchange_rate) {
		Exchange_rate = exchange_rate;
	}

	public int getPriDebt_amount() {
		return PriDebt_amount;
	}

	public void setPriDebt_amount(int priDebt_amount) {
		PriDebt_amount = priDebt_amount;
	}

	public int getDebt_amount() {
		return Debt_amount;
	}

	public void setDebt_amount(int debt_amount) {
		Debt_amount = debt_amount;
	}

	public Date getQDate() {
		return QDate;
	}

	public void setQDate(Date qDate) {
		QDate = qDate;
	}

	public String getAccountAge() {
		return AccountAge;
	}

	public void setAccountAge(String accountAge) {
		AccountAge = accountAge;
	}

	public String getCase_status() {
		return Case_status;
	}

	public void setCase_status(String case_status) {
		Case_status = case_status;
	}

	public Date getAssigned_dt() {
		return Assigned_dt;
	}

	public void setAssigned_dt(Date assigned_dt) {
		Assigned_dt = assigned_dt;
	}

	public String getAssigned_er() {
		return Assigned_er;
	}

	public void setAssigned_er(String assigned_er) {
		Assigned_er = assigned_er;
	}

	public Date getPreAssigned_dt() {
		return PreAssigned_dt;
	}

	public void setPreAssigned_dt(Date preAssigned_dt) {
		PreAssigned_dt = preAssigned_dt;
	}

	public String getPreAssigned_er() {
		return PreAssigned_er;
	}

	public void setPreAssigned_er(String preAssigned_er) {
		PreAssigned_er = preAssigned_er;
	}

	public Date getRecord_dt() {
		return Record_dt;
	}

	public void setRecord_dt(Date record_dt) {
		Record_dt = record_dt;
	}

	public String getRecord_er() {
		return Record_er;
	}

	public void setRecord_er(String record_er) {
		Record_er = record_er;
	}

	public Date getUpdate_dt() {
		return Update_dt;
	}

	public void setUpdate_dt(Date update_dt) {
		Update_dt = update_dt;
	}

	public String getUpdate_er() {
		return Update_er;
	}

	public void setUpdate_er(String update_er) {
		Update_er = update_er;
	}

	public String getReason() {
		return Reason;
	}

	public void setReason(String reason) {
		Reason = reason;
	}

	public String getCtCase_interest() {
		return ctCase_interest;
	}

	public void setCtCase_interest(String ctCase_interest) {
		this.ctCase_interest = ctCase_interest;
	}

	public Date getCtCase_d() {
		return ctCase_d;
	}

	public void setCtCase_d(Date ctCase_d) {
		this.ctCase_d = ctCase_d;
	}

	public Date getGvCCard_d() {
		return gvCCard_d;
	}

	public void setGvCCard_d(Date gvCCard_d) {
		this.gvCCard_d = gvCCard_d;
	}

	public Date getKiCCard_d() {
		return kiCCard_d;
	}

	public void setKiCCard_d(Date kiCCard_d) {
		this.kiCCard_d = kiCCard_d;
	}

	public Date getCpInterest_d() {
		return cpInterest_d;
	}

	public void setCpInterest_d(Date cpInterest_d) {
		this.cpInterest_d = cpInterest_d;
	}

	public Date getTnBadDebt_d() {
		return tnBadDebt_d;
	}

	public void setTnBadDebt_d(Date tnBadDebt_d) {
		this.tnBadDebt_d = tnBadDebt_d;
	}

	public Date getTnPress_d() {
		return tnPress_d;
	}

	public void setTnPress_d(Date tnPress_d) {
		this.tnPress_d = tnPress_d;
	}

	public Date getStInterest_d() {
		return stInterest_d;
	}

	public void setStInterest_d(Date stInterest_d) {
		this.stInterest_d = stInterest_d;
	}

	public String getCanCost_amount() {
		return CanCost_amount;
	}

	public void setCanCost_amount(String canCost_amount) {
		CanCost_amount = canCost_amount;
	}

	public Date getShPay_d() {
		return shPay_d;
	}

	public void setShPay_d(Date shPay_d) {
		this.shPay_d = shPay_d;
	}

	public String getDelayPay_months() {
		return DelayPay_months;
	}

	public void setDelayPay_months(String delayPay_months) {
		DelayPay_months = delayPay_months;
	}

	public String getPreLoanCash() {
		return PreLoanCash;
	}

	public void setPreLoanCash(String preLoanCash) {
		PreLoanCash = preLoanCash;
	}

	public String getBank_other() {
		return Bank_other;
	}

	public void setBank_other(String bank_other) {
		Bank_other = bank_other;
	}

	public Date getLCost_d() {
		return LCost_d;
	}

	public void setLCost_d(Date lCost_d) {
		LCost_d = lCost_d;
	}

	public String getLCost_amount() {
		return LCost_amount;
	}

	public void setLCost_amount(String lCost_amount) {
		LCost_amount = lCost_amount;
	}

	public Date getLPay_d() {
		return LPay_d;
	}

	public void setLPay_d(Date lPay_d) {
		LPay_d = lPay_d;
	}

	public int getLPay_amount() {
		return LPay_amount;
	}

	public void setLPay_amount(int lPay_amount) {
		LPay_amount = lPay_amount;
	}

	public String getPay_Notes() {
		return Pay_Notes;
	}

	public void setPay_Notes(String pay_Notes) {
		Pay_Notes = pay_Notes;
	}

	public String getCasePS() {
		return CasePS;
	}

	public void setCasePS(String casePS) {
		CasePS = casePS;
	}

	public String getA_Capital() {
		return A_Capital;
	}

	public void setA_Capital(String a_Capital) {
		A_Capital = a_Capital;
	}

	public String getA_CFInterest() {
		return A_CFInterest;
	}

	public void setA_CFInterest(String a_CFInterest) {
		A_CFInterest = a_CFInterest;
	}

	public String getA_Interest() {
		return A_Interest;
	}

	public void setA_Interest(String a_Interest) {
		A_Interest = a_Interest;
	}

	public String getA_BKInterest() {
		return A_BKInterest;
	}

	public void setA_BKInterest(String a_BKInterest) {
		A_BKInterest = a_BKInterest;
	}

	public String getA_Other() {
		return A_Other;
	}

	public void setA_Other(String a_Other) {
		A_Other = a_Other;
	}

	public String getA_Total() {
		return A_Total;
	}

	public void setA_Total(String a_Total) {
		A_Total = a_Total;
	}

	public String getA_SIF() {
		return A_SIF;
	}

	public void setA_SIF(String a_SIF) {
		A_SIF = a_SIF;
	}

	public String getB_Capital() {
		return B_Capital;
	}

	public void setB_Capital(String b_Capital) {
		B_Capital = b_Capital;
	}

	public String getB_CFInterest() {
		return B_CFInterest;
	}

	public void setB_CFInterest(String b_CFInterest) {
		B_CFInterest = b_CFInterest;
	}

	public String getB_Interest() {
		return B_Interest;
	}

	public void setB_Interest(String b_Interest) {
		B_Interest = b_Interest;
	}

	public String getB_BKInterest() {
		return B_BKInterest;
	}

	public void setB_BKInterest(String b_BKInterest) {
		B_BKInterest = b_BKInterest;
	}

	public String getB_Other() {
		return B_Other;
	}

	public void setB_Other(String b_Other) {
		B_Other = b_Other;
	}

	public String getB_Total() {
		return B_Total;
	}

	public void setB_Total(String b_Total) {
		B_Total = b_Total;
	}

	public String getB_SIF() {
		return B_SIF;
	}

	public void setB_SIF(String b_SIF) {
		B_SIF = b_SIF;
	}

	public Date getITDate() {
		return ITDate;
	}

	public void setITDate(Date iTDate) {
		ITDate = iTDate;
	}

	public String getInterest_Period() {
		return Interest_Period;
	}

	public void setInterest_Period(String interest_Period) {
		Interest_Period = interest_Period;
	}

	public String getInterest_kind() {
		return Interest_kind;
	}

	public void setInterest_kind(String interest_kind) {
		Interest_kind = interest_kind;
	}

	public BigDecimal getInterest_Rate() {
		return Interest_Rate;
	}

	public void setInterest_Rate(BigDecimal interest_Rate) {
		Interest_Rate = interest_Rate;
	}

	public BigDecimal getBK_Rate() {
		return BK_Rate;
	}

	public void setBK_Rate(BigDecimal bK_Rate) {
		BK_Rate = bK_Rate;
	}

	public BigDecimal getDisct_Capital() {
		return Disct_Capital;
	}

	public void setDisct_Capital(BigDecimal disct_Capital) {
		Disct_Capital = disct_Capital;
	}

	public BigDecimal getDisct_IT() {
		return Disct_IT;
	}

	public void setDisct_IT(BigDecimal disct_IT) {
		Disct_IT = disct_IT;
	}

	public BigDecimal getDisct_ctCaseIT() {
		return Disct_ctCaseIT;
	}

	public void setDisct_ctCaseIT(BigDecimal disct_ctCaseIT) {
		Disct_ctCaseIT = disct_ctCaseIT;
	}

	public BigDecimal getDisct_bkIT() {
		return Disct_bkIT;
	}

	public void setDisct_bkIT(BigDecimal disct_bkIT) {
		Disct_bkIT = disct_bkIT;
	}

	public BigDecimal getDisct_Other() {
		return Disct_Other;
	}

	public void setDisct_Other(BigDecimal disct_Other) {
		Disct_Other = disct_Other;
	}

	public String getLoanBank() {
		return LoanBank;
	}

	public void setLoanBank(String loanBank) {
		LoanBank = loanBank;
	}

	public String getStat_MailedCnt() {
		return Stat_MailedCnt;
	}

	public void setStat_MailedCnt(String stat_MailedCnt) {
		Stat_MailedCnt = stat_MailedCnt;
	}

	public String getStat_PullFLCnt() {
		return Stat_PullFLCnt;
	}

	public void setStat_PullFLCnt(String stat_PullFLCnt) {
		Stat_PullFLCnt = stat_PullFLCnt;
	}

	public String getStat_VisitedCnt() {
		return Stat_VisitedCnt;
	}

	public void setStat_VisitedCnt(String stat_VisitedCnt) {
		Stat_VisitedCnt = stat_VisitedCnt;
	}

	public String getStat_PMTAmt() {
		return Stat_PMTAmt;
	}

	public void setStat_PMTAmt(String stat_PMTAmt) {
		Stat_PMTAmt = stat_PMTAmt;
	}

	public String getStat_PTPCnt() {
		return Stat_PTPCnt;
	}

	public void setStat_PTPCnt(String stat_PTPCnt) {
		Stat_PTPCnt = stat_PTPCnt;
	}

	public String getStat_BPCnt() {
		return Stat_BPCnt;
	}

	public void setStat_BPCnt(String stat_BPCnt) {
		Stat_BPCnt = stat_BPCnt;
	}

	public String getStat_CalledCnt() {
		return Stat_CalledCnt;
	}

	public void setStat_CalledCnt(String stat_CalledCnt) {
		Stat_CalledCnt = stat_CalledCnt;
	}

	public String getCaseMarkContent() {
		return CaseMarkContent;
	}

	public void setCaseMarkContent(String caseMarkContent) {
		CaseMarkContent = caseMarkContent;
	}

	public String getSecondHand_type() {
		return SecondHand_type;
	}

	public void setSecondHand_type(String secondHand_type) {
		SecondHand_type = secondHand_type;
	}

	public String getTnBadDebt_amt() {
		return tnBadDebt_amt;
	}

	public void setTnBadDebt_amt(String tnBadDebt_amt) {
		this.tnBadDebt_amt = tnBadDebt_amt;
	}

	public int getOtherDebt_amt() {
		return otherDebt_amt;
	}

	public void setOtherDebt_amt(int otherDebt_amt) {
		this.otherDebt_amt = otherDebt_amt;
	}

	public String getPMS_flag() {
		return PMS_flag;
	}

	public void setPMS_flag(String pMS_flag) {
		PMS_flag = pMS_flag;
	}

	public String getInsider_amt() {
		return insider_amt;
	}

	public void setInsider_amt(String insider_amt) {
		this.insider_amt = insider_amt;
	}

	public String getOutsider_amt() {
		return outsider_amt;
	}

	public void setOutsider_amt(String outsider_amt) {
		this.outsider_amt = outsider_amt;
	}

	public Date getSider_d() {
		return sider_d;
	}

	public void setSider_d(Date sider_d) {
		this.sider_d = sider_d;
	}

	public int getG_ID() {
		return G_ID;
	}

	public void setG_ID(int g_ID) {
		G_ID = g_ID;
	}

	public String getProd_Name() {
		return Prod_Name;
	}

	public void setProd_Name(String prod_Name) {
		Prod_Name = prod_Name;
	}

	public String getBank_ID() {
		return Bank_ID;
	}

	public void setBank_ID(String bank_ID) {
		Bank_ID = bank_ID;
	}

	public String getBank_name() {
		return Bank_name;
	}

	public void setBank_name(String bank_name) {
		Bank_name = bank_name;
	}

	public String getBank_alias() {
		return Bank_alias;
	}

	public void setBank_alias(String bank_alias) {
		Bank_alias = bank_alias;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getID() {
		return ID;
	}

	public void setID(String iD) {
		ID = iD;
	}

	public String getO_or_C() {
		return O_or_C;
	}

	public void setO_or_C(String o_or_C) {
		O_or_C = o_or_C;
	}

}
